spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/todo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        format_sql: true
        generate_statistics: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    com.todo: debug
jwt:
  secret: todo$!$